### ISSUE TITLE
Dendron Uses Custom NanoID Length?

### ISSUE THREAD

**Issue by micharris42** [dendronhq/dendron#1044]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [X] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [X] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Only noticed it today, but for the past two weeks (since version 0.50) Dendron has been creating sixteen character NanoIDs instead of the normal twenty-one. I assume this is a result of the recorded bug fix: "only generate alphanumeric ids to be compatible with github pages urls".

However, after using  the fixFrontmatter Doctor command, my earlier notes still use twenty-one character NanoIDs.

Is there a command to normalize the Frontmatter throughout a Dendron Vault? Or, is there a setting to return the NanoIDs in the Frontmatter to the standard twenty-one?

Thank you.

**Comment by SeriousBug** [comment]
Hi! We unfortunately do not have any actions to normalize the IDs right now. However, mixing longer and shorter IDs should function correctly.

Are you experiencing any problems with these IDs? Do you prefer consistent IDs? Please let us know so we can come up with an actionable plan.

For reference, I decided to shorted the IDs after calculating the probability of collisions and finding that there is practically no risk of collisions even with a shorter length.

**Comment by micharris42** [comment]
I have not noticed any problems with the shorter IDs. On my part, it is a uniformity issue. The reason it stuck out to me was because I have been making an effort since Dendron switched from UUIDs to NanoIDs to work through my vault and update the frontmattter in all of my notes. 

My real concern is that Dendron now uses "Dendron-specific NanoIDs". Every generator I have come across uses the default twenty-one characters, and I have not seen an option for changing that to sixteen. I realize this is a very small change in the grand scheme of things, but it does seem to go against the mostly ubiquitous format of the rest of Dendron—Markdown, wikilinks, etc.—which is one of the advantages of a plain text note taking system.

**Comment by SeriousBug** [comment]
I understand your concerns. I think it makes sense to keep the default setting shorter since I think people would prefer shorter IDs, but I can certainly add a configuration option for Note ID length and a Doctor action to regenerate all note IDs. I should be able to get that out within 2 weeks, sorry for the trouble in the meantime.

**Comment by micharris42** [comment]
No trouble at all. Thank you for your time.

**Comment by SeriousBug** [comment]
Dendron 0.53 now uses 21 character NanoIDs for note ids once again.

You can use the `Dendron: Doctor` command, and then select the `regenerateNoteId` action to regenerate all your note ids. Regenerated note ids will be 21 characters long.

Using the Doctor command might display an error message, but it otherwise works successfully. I'll investigate the message, but please feel free to use it right away and just ignore the message.
