### ISSUE TITLE
Sometimes minutes from keystroke to reaction

### ISSUE THREAD

**Issue by funnym0nk3y** [dendronhq/dendron#1068]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

In some situations dendron gets extremely slow. It takes minutes from pressing the lookup shortcut (and also from choosing it from the command palette) to the opening of the lookup field. Unfortunately I can't reproduce it reliably. Nearly every function of dendron is affected. It creates a constant load on the CPU. Restarting vscode does not solve it. 

## Desktop (please complete the following information)

- OS: Win10
- Version: 0.52.0

## Additional context

Nearly every function of dendron is affected. 

## Dendron Log file

No logs here as they are also affected.

**Comment by funnym0nk3y** [comment]
Uninstalling dendron and all the associated extensions and reinstalling just dendron without MPE and the graph extension seemed to solve this problem.

**Comment by funnym0nk3y** [comment]
Apparently it does not solve the problem, sorry for the confusion.

**Comment by hikchoi** [comment]
Unfortunately there isn't enough information to diagnose what is happening here, but we will make note of this.
Can I ask which flavor of VSCode (and which version) you are using?

I personally have had issues with extensions (both Dendron and other) hogging up resources and blocking IO when I was using VSCodium. This was something that happened with a particular version of VSCodium, which was resolved by me moving to an official build or an insider build.

If you can go through some extension profiling within VSCode that would give us a lot of information, but this is a bit tedious and not something I want to ask you to do right away.
The low hanging fruit here is trying out a different flavor of VSCode: if your problem persists even after this, we will have a higher confidence that something is not right on our end (although not certain). Will you be willing to try this out?

Otherwise, it would be great if you can provide us some info about your VSCode flavor and a rough idea of how powerful your machine is, so that we can try to emulate a similar setup ourselves.
