### ISSUE TITLE
Support backreferences in `Refactor`

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#116]
Example

- files
```
lang.python.data
lang.ruby.data
lang.js.data
```

- refactor
```
match: lang.(.*).data
replace: lang.$1.d
```

- result
```
lang.python.d
lang.ruby.d
lang.js.dd
```

**Comment by hikchoi** [comment]
looking at the `RefactorHierarchyCommandV2` now, looks like we are fixed to doing a `(.*)(${match})(.*)` to pick the candidates.

I think removing that and simply letting the users input a full regexp pattern would cause a bit of friction as it's a pretty significant breaking change.

I propose that we add a separate command (say `RefactorHierachyFullRegexCommand`), or add an config to the existing one so that users can have a choice. (and let them pick the default behaviour).

**Comment by kevinslin** [comment]
I like that. Instead of doing a separate command, we can add an option
toggle to the existing command to go fully regex
