### ISSUE TITLE
Frontmatter Folding Automatically

### ISSUE THREAD

**Issue by micharris42** [dendronhq/dendron#1163]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [X] Misc (Choose this if your not sure)

## Describe the bug

As of the latest Dendron release, 0.55.1, the note frontmatter is now folding automatically. If the frontmatter is expanded, it will remain so until Dendron is closed. When Dendron is reopened, the frontmatter will once again be folded.

This is not mentioned in the [release notes](https://wiki.dendron.so/notes/fYU3mSfr096DYui0O2cRp.html), and is therefore most likely a bug.

## To Reproduce

1. Open a note. The frontmatter will be folded.
2. Expand the frontmatter. The frontmatter will remain expanded even if the note is closed and reopened.
3. Close and restart the program.
4. Note frontmatter will once again be folded.

## Expected behavior

That the frontmatter be expanded by default. If the frontmatter is expanded or folded, that Dendron remember between sessions.

## Desktop (please complete the following information)

- OS: Windows 10
- Browser: NA
- Version: Dendron 0.55.1, VSCodium 1.59.0

## Additional context

If this is an intended feature and Dendron now defaults to folding frontmatter, that there be a setting to change this behavior.

**Comment by SeriousBug** [comment]
Hi! Thanks for the report. There is in fact a setting to change this behavior: https://wiki.dendron.so/notes/f83c1d87-eac0-48f3-a5cf-8a69989d8ec1.html#autofoldfrontmatter

You can set `autoFoldFrontmatter` to `false` in your `dendron.yml` to disable this.

This feature was introduced several releases ago, and the default was intended to be `true`. However it seems that due to a bug the default setting was accidentally set to false, which was fixed in this release. Sorry for not communicating the change better! Please let us know if you have any other questions or issues.

**Comment by micharris42** [comment]
Thank you for the explanation. Have made the adjustment to my dendron.yml, and that has fixed it for me.

Closing this issue.
