### ISSUE TITLE
Create daily journal note without requiring active text editor

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#122]
## Context

Creating a daily journal will fail if you are currently not in an open editor (eg. the welcome page of VSCode).

This is a carryover from how scratch notes and journal notes work because they get added relative to a given hierarchy. The daily journal note does not require this.

## Proposal

Don't throw error when creating a daily journal note and you are not currently in a note

## Changes Required

- [CreateNote](https://github.com/dendronhq/dendron/blob/master/packages/plugin-core/src/commands/CreateNote.ts#L81)
    - [ ] `genFname` needs to take an additional property in opt, `requireActiveEditor?: boolean`
    - [ ] `genFname` should not throw an error if no active editor is present and the above flag is set

**Comment by bs** [comment]
So much for a 1 line fix :)

There are two identical methods that get called that throw this exception, one for journals and one for scratch notebooks.
`src.commands.createNote.genFname` & `src.utils.genNoteName`.

<img width="1464" alt="Screen Shot 2020-10-19 at 2 18 50 PM" src="https://user-images.githubusercontent.com/68/96513034-491ab680-1216-11eb-9856-aa4086314e2f.png">

A couple of thoughts/questions:

## Assumptions
- It seems like looking up editorPath is solely used to find the prefix (root node)
- root nodes, as looked up here in `genNotePrefix` are not yet intertwined with multi-vault notes

## Journal Behavior
- Since journal name is fixed, can we just remote this check? Are you thinking about supporting journals under a different root?

## Scratch Behavior?
- With the way they behave now, this check should fire if we're in a note
- Wouldn't it make more sense for the scratch to append to the full note path, rather than the root? Or is the idea that scratches belong on a root domain?
- If no note is open, what's the behavior?
    - create a scratch root node

## Two methods
- Reason for two methods?
- Can we nuke one and name the called method something more representative of the function?

**Comment by kevinslin** [comment]
so the reason you see this duplication is because of the server migration. 

- `CreateNoteCommand` is actually deprecated and will be removed after next week when we migrate existing users to server mode
- names for serer mode are now generated by `DendronClientUtilsV2.genNoteName`
    - loc: plugin-core/src/utils.ts
- dendron has 4 different `ADD_BEHAVIORS`
    - https://dendron.so/notes/5c213aa6-e4ba-49e8-85c5-1bdcb33ce202.html#defaultnodetypeaddbehavior
    - `asOwnDomain` is the only behavior that does not require a note to be active because it is a hardcoded path (all the other behaviors are relative of the current note)
