### ISSUE TITLE
PDF Attach/Import/Insert on Linux

### ISSUE THREAD

**Issue by 1beb** [dendronhq/dendron#1232]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

Reading through the wiki it appears there is some discussion about working with PDF documents attached or inserted into the dendron workspace. I read somewhere else that you could drag and drop into the tree view. None of these appear to work on Linux. 

## To Reproduce

Use Linux, try copy/paste from nautilus or drag/drop from nautilus into tree view. 

## Expected behavior

Attached PDF and saved into assets? I'm not sure what the anticipated behavior is supposed to be. 

## Desktop (please complete the following information)

- OS: Pop OS
- Browser: VS Code? 
- Version 21.04

**Comment by hikchoi** [comment]
Thanks for the report, there is a similar issue opened here: https://github.com/dendronhq/dendron/issues/1090

Pasting asset links into notes is a common use case for our users and we are planning to introduce a similar workflow as `paste image`. Currently we have `Dendron: Paste File`, but it doesn't copy from clipboard and requires users to manually type in the path for the file. In the end we think it should work like how it's requested in #1090 

> I read somewhere else that you could drag and drop into the tree view.

Are you referring to the VSCode's native file explorer tree view or Dendron's tree view (which is a web ui)? If this is not working in VSCode's native tree view, this may not be something we directly have control over and should be reported to the VSCode repo. Dendron's tree view currently doesn't support drag and drop.

Does this clarify your concerns? If you have any other outstanding issues, please comment. Otherwise this will be marked as duplicate and will be closed in 4 days.

**Comment by 1beb** [comment]
Thank you, I'll close here and add my comments to #1090
