### ISSUE TITLE
RFC: BDD-Light

### ISSUE THREAD

**Issue by nickolay-kondratyev** [dendronhq/dendron#1309]
## Context

RFC 25 BDD Light Discussion Thread. 

## Proposal
https://github.com/dendronhq/dendron-site/pull/187

## View Markdown Rendered Proposal 
https://github.com/dendronhq/dendron-site/blob/f45d9a3dc07cc7a0fe19b3824bc3383e7c2f7c29/vault/dendron.rfc.25-bdd-light.md

**Comment by nickolay-kondratyev** [comment]
Pull Request : https://github.com/dendronhq/dendron-site/pull/187

**Comment by kevinslin** [comment]
some thoughts:

- done BDD testing in the past (eg. its defacto in rails development) and like the readability of the output 
- nice that you can copy and paste the test output directly into the commit and have that be understandable
- where I've seen this run into trouble in the past is when people go overboard with verbs (eg. there's 10 different ways to do a positive assertion)
  - as long as we keep our verbs small and use the builtin assertions, I think doing BDD is fine
- our current tests don't adhere to BDD - this is fine but we'll want to be cognizant of how to introduce this going forward and how (or if its worth it) to format existing tests

**Comment by hikchoi** [comment]
Despite the risk of getting too much into the semantics and being nitpicky, I have a question to ask: with BDD-light, is the development _driven_ by behaviors, or are you suggesting that it should? If not, would it be better if we word the proposal to say that we are adopting the `Given-When-Then` structure and not call it BDD-light to avoid confusion?

I haven't personally done full-on BDD testing before (I have gone through a failed attempt at adopting though) so please correct me anywhere I'm not understanding.

From the proposal I get the feeling that what you are suggesting is that we adopt the Given-When-Then structure for describing our test going forward, and _only_ the structure. I know GWT was coined with the birth if BDD, but I feel like the GWT ways of structuring the test can be divorced with the idea of behavior driven development altogether. It simply is a nice way of organizing tests.  I am assuming since you aren't suggesting that we do BDD that my line of thinking is correct.

I love the proposal. I personally have struggled and spent embarrassing amounts of time trying to figure out what's breaking the tests so I would love a more readable and clear description of our tests. Also agree on the duplicate code for test setups. I always feel bad writing those. I wouldn't know what gotchas we will run into without actually trying to write the tests in this way myself, but at a surface level I have nothing to disagree with what you are suggesting we do.

I just feel like it's important to set a clear goal of this proposal so that we don't get side-tracked later down the line with how we (us, future team members, and contributors) think about tests. That is: _We are only taking the notion of `Given-When-Then` that is coined by the BDD folks to organize our tests because it is a nice way to structure tests even outside the context of BDD_. 

If what I'm saying is already implied in your proposal I'm fine with that. It's a bit late in the night and my brain is a bit foggy 😅

**Comment by jonathanyeung** [comment]
I haven't done too much BDD style testing in the past, but I like it! The read-it-like-English aspect of the style is great and something we should strive for. 

Not too much comments otherwise. In terms of how we adopt this, I think let's take a staggered approach.  Let's not spend too much time overhauling existing tests at the moment.  For new tests, let's try to implement it in this style.  As we need to refactor or expand on existing test sets, then let's convert over as it makes sense.

**Comment by SeriousBug** [comment]
I was just trying to write some tests and wanted to use BDD, but I'm not sure how to write tests like this for tests using `runLegacyMultiWorkspaceTest` (or other engine testing functions). For example with a test like this:

```ts
test("warns about long tests", (done) => {
  const FNAME = "test.note";
  runLegacyMultiWorkspaceTest({
    ctx,
    preSetupHook: async ({ vaults, wsRoot }) => {
      /* ... */
    },
    onInit: async ({ vaults, engine, wsRoot }) => {
      /* ... */
      expect(wikilinkDecorations.length).toEqual(1);
      expect(
        isTextDecorated("![[foo.bar.*]]", wikilinkDecorations!, document)
      ).toBeTruthy();

      done();
    },
  });
});
```

How would I turn this into a BDD-style? Either the "THEN" parts need to be inside `onInit` (would jest/mocha pick it up then?), or I would I have to duplicate this setup for each "THEN"?

**Comment by nickolay-kondratyev** [comment]
If we can we want to avoid the duplication as much as possible. 

In this case wonder whether we can move the runLegacyMultiWorkspaceTest() (without the expects) function into beforeEach/beforeAll and then record the [vaults, engine, wsRoot] for the THEN statements to use.
