### ISSUE TITLE
IDE independent tooling

### ISSUE THREAD

**Issue by xeruf** [dendronhq/dendron#1368]
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

I have just discovered this and am currently using org-roam.
I could imagine that some principles you lay out could be useful for my workflow,
because retrieval is indeed an afterthought currently.
But I do not want to use VSCode

## Describe the solution you'd like ##

IDE independent tooling (CLI/libs) to integrate with other tools such as Emacs org-roam

**Comment by hikchoi** [comment]
Thanks for bringing up this issue.
We currently do not have immediate plans officially support other IDEs at the moment, but our core logics are somewhat independent of VSCode. We currently have limited features exposed with our CLI, but we don't have public facing libraries that can be used for other tools.

That being said, we are always considering ways to expand beyond VSCode, and weighing the possibilities in many avenues. It is just not our current focus at the time.

Feel free to open another issue with more specific requests or comment on this thread if you still have some thoughts to share. You can also start a discussion thread [here](https://github.com/dendronhq/dendron/discussions) if you want the discussion to persist.

Since this is an area of interest that is very broad and vague (and also internally tracked), I'll mark it so that the bot can automatically close if there is no further activity.
