### ISSUE TITLE
Creating scratch note without an open file results an error

### ISSUE THREAD

**Issue by jojanaho** [dendronhq/dendron#141]
**Describe the bug**
Invoking "create scratch note" without any file opened results the following error:
`Command 'Dendron: Create Scratch Note' resulted in an error (Cannot read property 'selection' of undefined)`

**Expected behavior**
New scratch note created to root?

**Comment by kevinslin** [comment]
You're really killing it with the bug finding 😅

Good find, this is caused by this [line](https://github.com/dendronhq/dendron/blob/master/packages/plugin-core/src/commands/CreateNote.ts#L103)

It shouldn't throw an error if the `note add behavior === asOwnDomain`.

If you feel up to it, would you consider making a pull request? This should be a one line change and I already have integration tests for new note creation ([docs to run tests](https://www.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html))

If you pull the latest changes from Dendron, I should have fixed all the build errors too so it should just work now. 

If you can't, no worries either. I'll probably update it first thing next week!
