### ISSUE TITLE
`Show Preview` should not be available outside of a Dendron workspace

### ISSUE THREAD

**Issue by lnicola** [dendronhq/dendron#1545]
## Please select the area your Bug applys to.

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

It's annoying to have two `Show Preview` and maybe other Dendron commands (except `Initialize workspace`) that don't actually work, see #1540 for more context.

Filed as a bug because that's what it feels like.

**Comment by hikchoi** [comment]
There are still a few things we want to make sure before completely dropping `Show Preview`. Once we are confident about that, we will announce that it will be dropped. Note that if you don't have the additional extension installed, both commands will default to using our V2 preview.

**Comment by hikchoi** [comment]
This issue has been resolved with #1619 (released with v66)
As suggested, `Show Preview V2` is now named `Show Preview` and `Show Preview` is `Show Preview (legacy)`.
`Show Preview (legacy)` will only be enabled if you have installed Dendron MPE, and will otherwise be hidden from the command palette.
Both preview commands will now only be enabled and accessible if your active editor is a markdown file and Dendron is activated.

Also heads up that we have contributed upstream to VSCode itself in order to hide the extra preview button shown in the top right corner of the editor to reduce clutter and confusion. Stay tuned for this update! 
related: https://github.com/dendronhq/dendron/pull/1636

Please try it out and leave a comment if you still have concerns regarding this issue. Otherwise, I've marked this issue to auto-close in 4 days if there aren't further comments. No action will be needed if you don't have outstanding concerns.

**Comment by lnicola** [comment]
Looks great, thanks!
