### ISSUE TITLE
Add `dendron.createScratchNote` command

### ISSUE THREAD

**Issue by bwobst** [dendronhq/dendron#1730]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are possible) ##

- [ ] Onboard. Initial vault setup and import/export pods
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

I would like to use the scratch note functionality as described in the [documentation](https://wiki.dendron.so/notes/5c213aa6-e4ba-49e8-85c5-1bdcb33ce202/#scratch-note), but I do not want to click the UI button to enable that mode.

## Describe the solution you'd like ##

I would like a keyboard shortcut that auto-creates the appropriate scratch note at the current date/time. I would expect the behavior to be identical to creating a journal note via keyboard shortcut.

## Describe alternatives you've considered ##

I tried clicking the UI button to enable the scratch mode.

In the meantime I have simply created a single catch-all `scratchpad.md` standard note.

## Additional context ##

I'm on v0.69.1. I have not modified `dendron.yml` from its initial configuration.

I've confirmed that the available keybindings for `dendron.create*` are:
<img width="1121" alt="Screen Shot 2021-11-17 at 9 23 36 AM" src="https://user-images.githubusercontent.com/2824184/142250459-40a4af6d-6f6f-401f-a670-88edbd36bfa7.png">

**Comment by benhsm** [comment]
If I'm not mistaken, by default, pressing "ctrl+shift+s" brings up the lookup UI and activates the scratch modifier as if you clicked the UI button (I'm not sure how this differs on MacOS). As far as I can tell, it isn't very prominent in the text documentation, but I saw it being used that way in a video clip somewhere. Below is what I get on my system when I hit those keys, with UI focus on the lookup prompt:
![dendron_lookup_2](https://user-images.githubusercontent.com/93843523/142338813-bda4021c-9937-4f9b-8560-a18051d66b62.jpg)

The relevant action seems to be `dendron.lookupNote`, rather than `dendron.create`. The three keybinds below all point to the same action, but each passes in a different argument. The documentation that goes over how to customize this behaviour is [here.](https://wiki.dendron.so/notes/ad270a7d-2aed-4273-8319-eb6536e38b29/#enabling--modifier-2)

![dendron_lookup_1](https://user-images.githubusercontent.com/93843523/142339099-1bdd45eb-ee08-4468-888a-345a39530b2d.jpg)

**Comment by hikchoi** [comment]
Thank you @bwobst for the issue and @benhsm for the explanation.
@benhsm is right. This definitely is confusing. It has been mentioned in our community in the past.

We can create a separate command for each of those so that they don't share the same `dendron.lookupNote` key in the keyboard shortcut settings to fix this confusion.

In the mean time, what @benhsm suggested would do the trick. scratch note creation can be done using the keybinding <kbd>Ctrl</kbd>/<kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>S</kbd>

**Comment by bwobst** [comment]
Thanks @benhsm and @hikchoi for the quick responses. That solution works for me.
