### ISSUE TITLE
References showing inefficient order and then not showing up at all

### ISSUE THREAD

**Issue by Tycholiz** [dendronhq/dendron#1867]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Two things happening here:
1. I have a note at `aws.svc.SQS` and I am trying to make a reference to it. When typing "SQS" within the `[[]]`, I expect it to be at the top, yet it shows up near the bottom.
2. Once I delete the text that was producing the autocomplete dropdown, I can't get it to show up again unless I delete the `[[]]` entirely and start all over.

## GIF
![Dendron-reference-bug](https://user-images.githubusercontent.com/39745457/145335922-b512aea1-2f15-476b-90b7-303766f2c3fe.gif)

## Desktop (please complete the following information)

- OS: MacOS Catalina
- Browser: Chrome
- Version: 0.72.0

**Comment by Harshita-mindfire** [comment]
Thanks @Tycholiz for the bug report.  Can repro this one. Pinging @SeriousBug for more context regarding autocomplete.

**Comment by SeriousBug** [comment]
Hi! These are unfortunately limitations with Visual Studio Code. VSCode automatically orders the autocomplete items so we can't choose which ones should appear at the top.

For the autocomplete disappearing, could you try running the "Trigger Suggest" command? This is bound to `Ctrl+Space` by default, and the autocomplete should resume once you do that.

Let me know if these work for you, otherwise this issue will close in a few days.
