### ISSUE TITLE
Better git commit messages on sync

### ISSUE THREAD

**Issue by chmac** [dendronhq/dendron#2281]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [x] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

I have just discovered that dendron deleted all of my data in one pod, see #2280. It's frustrating that I don't know which instance of dendron made this commit. I also don't know anything about what operation caused the commit. I only have the commit message `update`.

## Describe the solution you'd like ##

More details in commit messages. For example, each dendron install could generate it's own unique id. A short ID would be fine. Then the commit message could be `update ${instanceId}`. Or even better would be a more verbose description of what triggered the commit with messages like "user triggered sync" or "automated sync", etc.

## Describe alternatives you've considered ##

I don't see any alternatives.

**Comment by SeriousBug** [comment]
How about something like this:

```
Dendron workspace sync

Synced vaults:
- vaultA
- vaultB

Dendron version: 0.79
Hostname: eclipse
```

Generating an ID might not be that useful since the user still has to search through their filesystem to find what the ID for that machine is. Hostnames are automatically set up in modern OSes during installation, and the user is much likelier to already know what the hostname for their machine is.

**Comment by chmac** [comment]
@SeriousBug Hostnames is an awesome idea. The "synced vaults" could be useful, maybe it will "leak" information between vaults. Not sure if that matters. In general I think each vault usually has its own git repo. Otherwise, the content looks great, and would help a lot in understanding what the history looked like...

**Comment by SeriousBug** [comment]
Sorry I didn't clarify, but the "Vaults" would be the vaults within that repository only. One repository could have more than one vault in it with in some conditions (multiple local vaults and workspace is in a repo, or a remote workspace vault that has multiple local vaults), so I thought might be useful.

There's no risk of leaking vault names because it will only list vaults that are included within that repository. So anyone who has access to the repository can also see the vaults already. But it's a little redundant, so I think I'll skip that.

**Comment by chmac** [comment]
@SeriousBug Ahh, I understand how. True, there can indeed be multiple vaults in a single repo. The version and hostname seems like a great addition.

I wonder if there's any privacy concerns with using hostname directly. For example, if I was pushing to a shared vault, would I want my hostname revealed. I'd probably slightly prefer that each dendron instance has a name, but that's a much more complicated approach. Maybe using the hostname is an acceptable trade off.

Does it warrant adding a config flag?

What about having a dendron setting that's called hostname, and if blank, it uses the system's hostname? That way paranoid folks (like myself! 😄 ) could set a unique dendron only name per vscode instance. Although now that I think about it, my settings are all synced! Maybe I could exclude it.

Anyway... Just a little food for thought this morning...

**Comment by SeriousBug** [comment]
Dendron 0.81 now includes better commit messages for the sync. Please let us know if you have any issues with the sync message.
