### ISSUE TITLE
Support for virtual file systems

### ISSUE THREAD

**Issue by sbatten** [dendronhq/dendron#2761]
## Please select if your request is either something new or an enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

Generally applies to the entire extension

## Is your feature request related to a problem? Please describe ##

I'd like to be able to use github.dev or vscode.dev to open my repo and take notes. Right now this is not possible because dendron cannot work in a virtual file system.

## Describe the solution you'd like ##

Support virtual file systems for better vscode web support.

**Comment by Harshita-mindfire** [comment]
Thanks @sbatten for the feature request.

**Comment by Harshita-mindfire** [comment]
Hey @sbatten , Dendron does have a web extension now!
It has very limited functionality currently, but we are planning to extend them as per the usage patterns
Read more [here](https://wiki.dendron.so/notes/svmryfk3iwexs7pfty1j6at/#quickstart)

**Comment by sbatten** [comment]
hi @Harshita-mindfire I've been playing around with this in vscode.dev. I'm happy to see the extension loading and some commands showing up. It seems some really useful commands are still not there yet, like "Create Daily Journal", also a few other issues I see are:
- Incomplete note lookup results
- errors when opening notes with note lookup (see below)
- opening a non-dendron workspace with remote repositories extension still errors on desktop when opening
<img width="331" alt="image" src="https://user-images.githubusercontent.com/6561887/196993057-2541e9e5-49c1-4a96-9672-fe3fc9ce4b81.png">

**Comment by cori** [comment]
I'm a bit hesitant to open a new issue here, since it seems similar but this is not working at all for me - let me know if a new issue is preferred.

When I load GitHub.dev with synced settings and Dendron enabled, code spaces tries to install the extension but then has a "problem with initialization". 

<img width="463" alt="dendron init issue" src="https://user-images.githubusercontent.com/46317/221408866-65976f64-7b32-432f-bbec-65fe49e0c6c1.png">

I'm just starting to poke around codesoaces, so I'm not that familiar with the environment, but because of the init issue I don't have any Dendron commands so I can't attach a log using the built-on command, but if I can gather additional data let me know.

If I load my config in _vscode.dev_ (or within the Blink Shell, FWIW) I don't get the error, but none of the Dendron commands are installed - the only Dendron-related command I see is `Paste Image`
