### ISSUE TITLE
Dendron not starting behind firewall

### ISSUE THREAD

**Issue by tveulemans** [dendronhq/dendron#332]
I have been able to install the dendron extension on my work laptop and to launch the command 'Initialize Workspace', but dendron does not start - as far as I can see this is linked to my being behind a firewall. 

I get the following error message (`___.___.___` stands for proxy string): 
```
{"ctx":"ReloadIndex.execute","error":{"name":"RequestError","message":"Error: Invalid protocol: ___.___.___:","cause":{},"error":{},"options":{"url":"http://localhost:52429/api/workspace/initialize","qs":{},"body":{"uri":"c:\\Users\\xxx\\Dendron","config":{"vaults":["c:\\Users\\xxx\\Dendron\\vault"]}},"json":true,"method":"POST","simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}},"msg":"unable to initialize engine"}
```

OS: Windows 10 (no admin rights)

Is there a way to run Dendron behind a firewall?
(Otherwise, feel free to reclassify as question and close.)

**Comment by kevinslin** [comment]
Hmm, this is interesting. Dendron starts a local server in order to index your notes. Does your firewall block local connections?

We have an incoming fix for this use case which involves starting Dendron on a custom port and then whitelisting that port in your firewall. Is that something that you are able to do (whitelist a local port)?

**Comment by tveulemans** [comment]
Hi,

I think the firewall blocks local connections: I tried to connect to http://localhost and http://127.0.01 and get a message "This site can't be reached". 127.0.0.1 refused to connect."

Unfortunately I cannot change the firewall's configuration (I would need to go through IT and I'm quite sure they won't accept).

If I understand correctly, I won't be able to use Dendron (at least on my work computer), right?

**Comment by kevinslin** [comment]
Yeah, Dendron currently requires that you can connect to a local server on your computer. The corporate firewall doesn't usually affect `localhost` connections since this is a connection originating from your computer. This usually indicates some custom software running on your computer.

A simple test to make sure that localhost is blocked:  start a new server using the command line and try connecting to it
```sh
# python2
python -m SimpleHTTPServer

# this starts a server on localhost:8000
curl localhost:8000

# you should see the following
127.0.0.1 - - [09/Nov/2020 07:13:10] "GET / HTTP/1.1" 200 -
```

If it does turn out to be the localhost issue then you're right, it will be tough to use Dendron on your work computer at this time. There are ways of getting around this using proxies or updating your computer's hostnames but your companies IT probably won't like it. 

We do plan on releasing a remote version of Dendron early 2021 which should help unblock you in that case.

**Comment by tveulemans** [comment]
Hi Kevin,

Many thanks for the input!

I have access to Python (3) but could not run the command above. I ran python -m http.server but do not get back the command prompt, and so cannot input `curl localhost:8000` command.

I strongly suspect it is linked to IT policies (I had a similar issue when trying to connect to my modem through localhost).

I'll keep an eye out for the remote version then (hopefully it will still build on top of VS Code and not require installing a local program, which would not work for me).

**Comment by kevinslin** [comment]
Got it. Yeah, that sounds like an IT issue. Timeline for remote version is going to be beginning of 2021 (most likely January). It'll be announced either in our discord or twitter at that point!

- https://twitter.com/dendronhq
- https://discord.gg/AE3NRw9

**Comment by tveulemans** [comment]
Hi @kevinslin, I have been keeping an eye on Twitter and I am impressed by the frequency of releases and the progress made on the application! I am looking forward to giving it a try. Do you still intend to release a remote version? Will it require the installation of additional software? Do you have an updated timeline?

**Comment by tveulemans** [comment]
Hi @kevinslin, do you still intend to release a remote version? Will it require the installation of additional software? Do you have an updated timeline?
