### ISSUE TITLE
Preview layout is not retained after a note is renamed

### ISSUE THREAD

**Issue by konrad-jamrozik** [dendronhq/dendron#353]
**Describe the bug**
If I have a note preview open to the side, if I rename the note with `Dendron: Rename Note`, the preview closes, and there is no easy way to reopen it on the side from the keyboard.

**To Reproduce**
1. Start with some note, e.g.:
![image](https://user-images.githubusercontent.com/4429827/99203833-aa2ba080-2768-11eb-9438-7a6107d3c2ec.png)
2. Execute `Dendron: Show Preview`
![image](https://user-images.githubusercontent.com/4429827/99203854-b879bc80-2768-11eb-9cc6-f78039798b37.png)
3. Observe the preview is on the side:
![image](https://user-images.githubusercontent.com/4429827/99203877-c16a8e00-2768-11eb-8598-2c34fb0b0f57.png)
4. Execute `Dendron: Rename Note`
![image](https://user-images.githubusercontent.com/4429827/99203888-ccbdb980-2768-11eb-9684-43f3afd1647a.png)
5. Observe the preview has closed:
![image](https://user-images.githubusercontent.com/4429827/99203916-dfd08980-2768-11eb-9f05-9a5a20495808.png)
6. Observe any attempt at reopening the preview with `Dendron: Show Preview` doesn't help. It remains in the same place.

**Expected behavior**
On step 5, the preview should remain being open on the side, as visible in step 3.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows Version 2004 (OS Build 19041.630)

**Additional context**
Observe the standard VS Code preview functionality has something called `Open Preview to the Side`, so maybe source code of it might help solving this problem:
![image](https://user-images.githubusercontent.com/4429827/99203721-4d2fea80-2768-11eb-8ced-5224b5c29378.png)

**Dendron Log file**
I believe logs are not relevant here.

**Comment by kevinslin** [comment]
This is because rename is a composition of create new note + delete old note + close current editor + open new editor. 

1) There's a few ways to fix this: we could detect whether a preview window is open on the side and make sure that the preview for the new note is also open.
2) Markdown preview has an option to always open the preview to the side: https://dendron.so/notes/401c5889-20ae-4b3a-8468-269def4b4865.html#prevent-newly-opened-files-from-replacing-the-preview-pane

We're planning on making a bunch of changes to preview in December #341 so would bundle this as part of those changes

**Comment by aleksey-rowan** [comment]
@konrad-jamrozik, this doesn't seem to be a problem with the V2 Preview. The preview tab remains open to the side, although it does flashes to the previous note before showing the renamed one again.
