### ISSUE TITLE
Make a meaningful standalone title for daily journal notes

### ISSUE THREAD

**Issue by nickolay-kondratyev** [dendronhq/dendron#3859]
## Describe the bug

When a new journal note is created, exmaple: `daily.journal.2022.12.10.md` 

The title of the note is going to be `10` which isn't very helpful title of the note. 

## Expected behavior

For the title of the note to carry meaning while standalone, a simple first step is to just add the full date into the title. Such as instead of putting `10` put `2022-12-10`.

**Comment by micharris42** [comment]
Hello @nickolay-kondratyev, are you using the [Dendron: Create Daily Journal Note](https://wiki.dendron.so/notes/9stxbnf9hxmxt76se5dtx2b/) command? 

This automatically fills the note's title frontmatter with "YYYY-MM-DD". Using your example above, the note `daily.journal.2022.12.10` would be shown as titled "2022-12-10" in the Dendron preview, the Graph View, and the Tree View.

Does this address your issue?

**Comment by tlylt** [comment]
To reproduce the behavior as per @nickolay-kondratyev ,
- `ctrl+l` to open look up
- manually type in the filename, e.g `daily.journal.2022.12.12`
- choose to create a new file

The title will then become `12`.

As highlighted by @micharris42
- clicking on the date in the calendar view and
- using keyboard shortcut `ctrl+shift+i`,

will create the daily journal with the correct title of `yyyy-mm-dd`

**Comment by hikchoi** [comment]
Thanks @micharris42 and @tlylt for the responses.

Yes, this has been brought up a few times and our resolution here was to apply note traits when using the `create daily journal` command.

We decided not to try to infer from the bare hierarchy during normal lookup to modify how the title is being generated. Generating the title based on the leaf node's hierarchy name is a sensible default for most cases, and we encourage users to create or use existing note traits to create notes that should follow special instructions on create. We would prefer to note add side effects to lookup moving forward.

That being said, I can think of a future enhancement here where during normal lookup, we match the lookup query with existing note traits so that the mental gap is filled.

I can't say exactly how and when (or even if that's _right_); just a quick idea I had on this matter.

@nickolay-kondratyev  In the time being, does what @micharris42 work out for you?
