### ISSUE TITLE
@dendronhq/dendron-cli@latest (@dendronhq/dendron-cli@0.124.1) fails on @dendronhq/api-server@^0.124.0 dependency (which is not published yet)

### ISSUE THREAD

**Issue by a-kplatek** [dendronhq/dendron#3976]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [X] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

@dendronhq/dendron-cli@latest (@dendronhq/dendron-cli@0.124.1) fails on @dendronhq/api-server@^0.124.0 dependency (which is not published yet)

## To Reproduce

run:
`npm install @dendronhq/dendron-cli@latest`

## Expected behavior

Package is installed successfully

## Desktop (please complete the following information)

```
npm -v
10.4.0

marvel-docs node -v
v18.17.1
```

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here

**Comment by kondratyev-nickolay** [comment]
Other [dependencies in NPM](https://www.npmjs.com/package/@dendronhq/dendron-cli?activeTab=dependencies) of dendron-cli also need to be published:

- [@dendronhq/api-server](https://www.npmjs.com/package/@dendronhq/api-server) 
- [@dendronhq/common-all](https://www.npmjs.com/package/@dendronhq/common-all) 
- [@dendronhq/common-server](https://www.npmjs.com/package/@dendronhq/common-server)
- [@dendronhq/dendron-viz](https://www.npmjs.com/package/@dendronhq/dendron-viz) 
- [@dendronhq/engine-server](https://www.npmjs.com/package/@dendronhq/engine-server) 
- [@dendronhq/pods-core](https://www.npmjs.com/package/@dendronhq/pods-core) 


It appears to be some issue with publishing process, since the dependencies already have the 0.124.0 version in their package.json files. But that version is not reflected in the npm registry.

Example:
- [api-server/package.json#L3](https://github.com/dendronhq/dendron/blob/master/packages/api-server/package.json#L3) has 0.124.0 version
- [NPM api-server versions](https://www.npmjs.com/package/@dendronhq/api-server?activeTab=versions) 0.122.0 version is latest in NPM.

**Comment by kevinslin** [comment]
this has been fixed in the latest version of dendron-cli (0.124.2)
