### ISSUE TITLE
Stand Alone Vaults or Workspace Agnostic

### ISSUE THREAD

**Issue by flammehawk** [dendronhq/dendron#402]
**Is your feature request related to a problem? Please describe.**

I get frustrated if I simply want to have a Vault inside another vscode Workspace.
Example could be, I'm working on a Project and have a docs folder and I want to have this docs folder be a dendron Vault currently that is only possible by having two code instances open, one for my Code / Project and one for my Docs.
This reduces the likely hood of me actually writing the docs while working on the code.

**Describe the solution you'd like**

If dendron becomes Workspace agnostic.
Currently it looks for a `dendron.code-workspace`  file. 
Which it shouldn't in my Eyes instead it should look for either a` .dendron.config` file in the root of a folder to check if it is a dendron folder. Or checking inside the `*.code-workspace`  file of the workspace if a Setting like dendron active exists, which could link to a separate config file or hold the dendron config inside the `*.code-workspace file`

**Describe alternatives you've considered**

A way to initialize a standalone Vault anywhere in the file system. 

**Additional context**
if the approach of an `.dendron.config` file is taken it could be used to hold vault specific configs. Maybe even making it easier to add vaults to an existing Dendron Workspace for Multi-Vault. 
And the `*.code-workspace` file holds actual configuration that affects all vaults / sets defaults for vaults.

**Comment by ScriptAutomate** [comment]
Ah, I see what you're wanting: for Dendron vaults to be your [Docs-as-Code]() `docs/` directory inside of projects! That would be super cool. Would the goal be to have a publishable vault for docs that people could view on something like GitHub/GitLab Pages, Netlify, etc. publicly for a project? While also providing the functionality of a dendron vault in your code editor when working on the code base for that project, and also having the ability for the vault to be included within a broader Dendron workspace in general?

This would be excellent. I'm often juggling Hugo, Sphinx, and Jekyll (non-Dendron) approaches to docs, depending on the code project, and I would love to default to Dendron vaults in my personal projects because of the Jekyll docs site publishing feature.

**Comment by flammehawk** [comment]
Yes that was the target mostly. 
If my Project has a ci pipeline anyway I can have one for the docs as well. 
No additional hassel and easier to actually write the docs. 
And to get my work to consider it I would only need to find a way for it to be integrated with intelij IDEs xD but that is a whole different can of worms.

**Comment by flammehawk** [comment]
This possibly relates to #41 and #9

**Comment by flammehawk** [comment]
And just found #322 that is possibly related as well.

**Comment by kpathakota** [comment]
Yes, let's close this one in favor of #322
