### ISSUE TITLE
Vaults keep their original path

### ISSUE THREAD

**Issue by alexisargyris** [dendronhq/dendron#43]
**Describe the bug**
Vaults seem to keep their original path.

**To Reproduce**
1. At PC1 create a dendron workspace containing a default vault.
2. Create a github repository and upload the vault you just created.
3. Clone the repository at PC2.
4. Attempt to open the vault's files.

**Expected behavior**
See the vault's contents.

**Screenshots**
I get an error message: "Unable to resolve workspace folder".

![image](https://user-images.githubusercontent.com/1640855/88087229-42d25b00-cb91-11ea-9549-2692cc7c07aa.png)

**Desktop**
 - OS: Win10
 - Browser: Chrome
 - Version: 83

**Comment by kevinslin** [comment]
this is because by default, Dendron sets the root as an absolute path. this will be updated in the new initialization script that will set these values as relative paths so you are able to use it between computers. to fix it in an existing workspace, update the `folders.path` value and the `dendron.rootDir` value in `dendron.code-workspace` to be relative files. 

you can see [this](https://github.com/dendronhq/dendron-template/blob/master/dendron.code-workspace) for an example

**Comment by alexisargyris** [comment]
Yes, the workaround works. Please note that the sample template should mention "path": "vault.main". Do you want to keep this open?

**Comment by kevinslin** [comment]
yeah, I'm pushing the new default this evening and will close it then :)

**Comment by kevinslin** [comment]
fixed in 790ef503225e5b18a78e3e62e847ba8b2adfd8d0
