### ISSUE TITLE
templates independent of schema

### ISSUE THREAD

**Issue by ikethefifth** [dendronhq/dendron#459]
**Is your feature request related to a problem? Please describe.**
In order to use a template, it needs to be attached to a schema. Some of my notes do not fit neatly into schemas, but I would still like the same template for them due to them being in the same domain.

**Describe the solution you'd like**
I would like to attach a template to a domain, such as project or project.foo. When I make a new note that starts with the chosen domain, it should generate using that template even if it has a long path like project.stuff.more.lots.mynote.

**Describe alternatives you've considered**
I've tried to make this work within the schema system but because the paths can be arbitrary lengths and the names don't follow a pattern, the schema doesn't work.

**Additional context**
N/A

**Comment by kevinslin** [comment]
thanks for the request. we want to add the option of a default template for notes. adding this to the backlog

**Comment by kpathakota** [comment]
IMO, this feature request is completed due to the presence of the `insert note` command for templates. See this note for more details: https://wiki.dendron.so/notes/861cbdf8-102e-4633-9933-1f3d74df53d2.html 

From the initial note, I see you'd like these to be automatically applied based on hierarchy but I think that would actually just entail simplifying schemas (and allowing for things such as all notes under a hierarchy to be specified). 

@ikethefifth - closing, feel free to open if you disagree.
