### ISSUE TITLE
Deep hierarchies and wiki links

### ISSUE THREAD

**Issue by alexisargyris** [dendronhq/dendron#47]
I am not sure if this is a bug or a feature request. It concerns the interaction between Dendron and the wiki links feature of [Markdown Notes](https://marketplace.visualstudio.com/items?itemName=kortina.vscode-markdown-notes).

**Describe the bug**
Scaling of hierarchies when combined with wiki links becomes quickly unworkable.

**To Reproduce**
1. Create a vault with a hierarchy of files going a few levels deep.
2. Attempt to set a wiki link between two files

**Expected behavior**
Being able to select a file from the popup.

**Screenshots**
You end up with something like this. You can't see the target file title.
![image](https://user-images.githubusercontent.com/1640855/88130510-70e08b00-cbe3-11ea-961d-9e199fb05e3c.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chome
 - Version: 83

**Additional context**
Why go so many levels deep? Because you want to set custom keys in the individual files' frontmatter. Should the file titles be shorter and make use of the frontmatter's title key?

Additional issues:
- What about spaces? Are they allowed or not? If not, use a hyphen or an underscore?
- What about titles with non-latin character sets? Allowed or not?
- Small inconvenience: when an option is selected from the wiki links popup, it gets inserted with the ".md" extension. However if you then attempt to navigate there, Dendron looks for "xxx.md.md" and proposes to create it.

Given Dendron's current roadmap which is the safest way forward? Use only latin, hyphenated, short file titles?

**Comment by kevinslin** [comment]
### Thoughts on deep hiearchies
- its true that due to the nature of the the links, the longer the hierarchy, the longer the link
- would argue that this is one of those **its a feature not a bug** cases - if you end up with really long hierarchies, you might have some opporunities to optimize

- an alternative to the hierarchy you've proposed
```
writing.md
writing.part.1.md
writing.part.2.md
writing.chapter.1-1.md
writing.chapter.2-1.md
...
```
- key points to note: instead of going down, we are flattening the hiearchy into distinct parts
- you can add links from writing to parts and parts to chapters using [journal notes](https://github.com/dendronhq/dendron-template/blob/master/vault/pro.dendron.topic.special-notes.md#journal-note)


- if you really want to go with the hierarichal means of organizing, you could make each path shorter and use the `desc` property of the schema for the long name
```
wr.md
wr.part1.md
wr.part1.chapter1.md
wr.part1.chapter1.section1.md

```

### Additional issues
- What about spaces? Are they allowed or not? If not, use a hyphen or an underscore?
  - spaces are not allowd in the file names. currently, we recommend using '-' for space
- What about titles with non-latin character sets? Allowed or not?
  - non-latin characters sets should be allowed but haven't been extensively tested yet so feel free to file an issue if you encounter one
- Small inconvenience: when an option is selected from the wiki links popup, it gets inserted with the ".md" extension. However if you then attempt to navigate there, Dendron looks for "xxx.md.md" and proposes to create it.
  - this is because there's a different extension that hadnles wiki links vs dendron nav. we ended up forking it so we can make faster updates. can you submit this as an issue?

**Comment by alexisargyris** [comment]
Thanks for that. A few questions:

- how to reference a note's front matter key values from the note's text?
- if, instead of using a hierarchy, I structure multiple pieces of text by connecting them with wiki links (or journal notes) how can I display the whole text? Do you plan to support some kind of transclusion mechanism?

**Comment by kevinslin** [comment]
### how to reference a note's front matter key values from the note's text?

currently not possible but its on the roadmap: https://github.com/orgs/dendronhq/projects/1

### if, instead of using a hierarchy, I structure multiple pieces of text by connecting them with wiki links (or journal notes) how can I display the whole text? Do you plan to support some kind of transclusion 
mechanism?

You can [peek](https://github.com/dendronhq/dendron-template/blob/master/vault/pro.dendron.tips.md#peeking) at notes linked by wiki-link. Have also added native transclusion in the roadmap: https://github.com/orgs/dendronhq/projects/1

**Comment by alexisargyris** [comment]
Great, thanks
