### ISSUE TITLE
Install Dendron and Recommended Extension

### ISSUE THREAD

**Issue by h-spiess** [dendronhq/dendron#476]
Hey,

I'm installing Dendron but I'm a bit confused about all the recommended extensions and dendron-specific forks. 

Are the current recommended extensions still the forked versions?
Dendron Markdown Preview enhanced
Dendron Markdown Shortcuts
Dendron Markdown Links
Dendron Snippet Maker

Dendron Paste Image

And what about: Dendron Markdown Notes? That is not recommended anymore but neither is the original extension Markdown Notes? 
And how might Markdown All in One be related?

Thank you very much. I don't know if I screwed something up with the extensions because I also tried Foam which uses the original versions where the Dendron ones are forked from.

Thanks a lot in advance and keep up the great work. :)

**Comment by kevins8** [comment]
Thanks for the reminder for me to update the extension list. Neither
Dendron Markdown Notes or Markdown notes is required anymore since we've
built them from the ground up to be inside Dendron.

Markdown All in One is a separate extension. I would not recommend
installing it since its known to interfere with other functions. Its
recommended because VSCode automatically recommends extensions for given
files.

Hope that helps!

**Comment by kevinslin** [comment]
Dendron Markdown Notes is now unpublished
