### ISSUE TITLE
Vault specific journal files

### ISSUE THREAD

**Issue by jeffabailey** [dendronhq/dendron#523]
## Please Select if your Request is Either something new or an Enhancement ##

- [ X ] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ X ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

When creating a Daily Journal with more than one vault in a vscode workspace the markdown file can't be created in a specific vault.

## Describe the solution you'd like ##

If there are multiple vaults in a vscode workspace ask which vault to create the markdown file in.

## Describe alternatives you've considered ##

I can't think of any, but right now I am moving the journal file into the appropriate vault after creation.

## Additional context ##

I can provide some if needed.

**Comment by kpathakota** [comment]
@jeffabailey - sorry for the late response but this config should be what you're looking for: https://wiki.dendron.so/notes/f83c1d87-eac0-48f3-a5cf-8a69989d8ec1.html#lookupconfirmvaultoncreate 

Just drop this at the end of dendron.yml and you should be golden
```
lookupConfirmVaultOnCreate: true
```

Closing since this should already exist. Please reopen if you're still finding issues here @jeffabailey
