### ISSUE TITLE
New journal note fails

### ISSUE THREAD

**Issue by alexisargyris** [dendronhq/dendron#56]
**Describe the bug**
Journal notes don't seem to work.

**To Reproduce**
1. Open a note
2. Enter the command "Dendron: New Journal Note"

**Expected behavior**
Open the journal note.

**Screenshots**
I get this:
![image](https://user-images.githubusercontent.com/1640855/88359178-61e01100-cd7a-11ea-8c05-c32cfb5e7025.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 84

**Comment by kevinslin** [comment]
are you able to reproduce it? If so, when you do - can you run the following command `>Dev:Dendron: Open Logs` and add the output to the issue?

**Comment by alexisargyris** [comment]
Here you are.
[dendron.log](https://github.com/dendronhq/dendron/files/4972152/dendron.log)

**Comment by kevinslin** [comment]
Thanks for the logs. So the error is because Dendron tried to make a backlink to the original note but couldn't find it. There's all sorts of reasons this could be. We actually rolled back the backlinking feature and instead are just copying the link into the clipboard when you create a new journal. Changes are live in 0.3.45 of Dendron. 

Created a new issue to propose different means of doing backlinks [here](https://github.com/dendronhq/dendron/issues/57). Take a look at that and let me know if you have preferences for the defaults/configurations.
