### ISSUE TITLE
Ctrl-hover should NOT create a new note

### ISSUE THREAD

**Issue by af4jm** [dendronhq/dendron#564]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [x] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Describe the bug

when the mouse pointer is over a broken wikilink, pressing Ctrl creates the link

## To Reproduce

I'm refactoring a note, I create my new TOC (which is going to point to the new child files, then I start extracting files... if I leave my mouse over one of the broken links and press Ctrl (usually as part of a cut or paste), a new note is created, even though per documentation, I have NOT triggered that to happen.

note that I can't just key in the new TOC after the pages are created, because I'd have to re-type the entire filename without help, because there's no support for auto-complete except after typing `[`, so since I'm typing after `|`, Dendron has nothing for me

The "work-around" is to manually delete the file, and depending on exactly what I was doing, may also involve going to git's pending changes to get back the text that was supposed to move

## Expected behavior

Creating a note should require a mouse click, not just typing something with the mouse pointer accidentally somewhere else

## Desktop (please complete the following information)

- OS: Windows
- Version latest VSCode (1.54.3) & Dendron (0.33)

## Additional context

very bizarre behavior, mouse-click functionality triggered without a mouse click, 25+ years as a dev I've never seen that one before... which is kinda cool

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by kevinslin** [comment]
heads up that this is addressed in the latest release: https://wiki.dendron.so/notes/9bc92432-a24c-492b-b831-4d5378c1692b.html#goto-note-command

**Comment by af4jm** [comment]
I just updated to 0.36.2, and Ctrl-hover still creates the note... do I need to add a setting somewhere?

**Comment by kevinslin** [comment]
Yes, this requires an update in `dendron.yml`:
https://wiki.dendron.so/notes/9bc92432-a24c-492b-b831-4d5378c1692b.html#goto-note-command
This is to preserve backward compatibility with current behavior. It's
default in new workspaces and we'll slowly migrate existing workspaces over

**Comment by aleksey-rowan** [comment]
Sorry for bringing up an old issue, but why was the `Ctrl + Click` option of creating notes removed? Now there is not mouse way to create a missing note, it can only be done through the keyboard.

**Comment by kevinslin** [comment]
This functionality still exists, you need to enable it now by setting
`noAutoCreateOnDefinition` to true in your dendron.yml

The reason we made this the default was because people didn't expect the
behavior of a note being created based on hover. That being said, we're
currently reconsidering making the default behavior to be `createByDefault`
unless disabled

**Comment by aleksey-rowan** [comment]
> The reason we made this the default was because people didn't expect the behavior of a note being created based on hover.

Apologies, I wasn't making myself clear. I'm talking about creating a note by clicking on a link while holding down the `Ctrl` (not merely hovering over a link).

Was this ever a feature to begin with? I realized I can't really tell because if `noAutoCreateOnDefinition` is disabled, there is no time to click on a link since the `hover` event would be fired first anyway.

If creating missing notes on `Ctrl + Click` was never a thing, could it be added?

**Comment by kevins8** [comment]
Ah, got it. I think once upon a time this might have been a feature but we
might have cut this when we consolidated features. If you create a separate
feature request, we can investigate adding that back in
