### ISSUE TITLE
Startup performance improvements

### ISSUE THREAD

**Issue by kpathakota** [dendronhq/dendron#573]
Dendron is starting to get a little slow when reloading with a large number of notes. Need to invest in a caching solution to update the speed to a reasonable value.

**Comment by konrad-jamrozik** [comment]
Big +1. I just measured: upon first open of VS Code it 45 seconds until I got "Starting dendron..." pop-up and another 7 until it actually started. 52 seconds in total. I have only 31 markdown files in Dendron.

This is a significant adoption barrier for me. I am trying to condition myself to use Dendron instead of desktop OneNote for taking notes, but OneNote rarely start in more than 2-3 seconds, in spite of me having over thousand pages in it.

**Comment by kpathakota** [comment]
@konrad-jamrozik  - something else might be going on for you because for 31 files, this should be extremely quick. Do you think you could file another issue with your logs? I think it'd be worth taking a look at them separately (in addition to these performance improvements).

**Comment by konrad-jamrozik** [comment]
@kpathakota will do! Thx for the insights.

**Comment by konrad-jamrozik** [comment]
I was not yet able to obtain full logs, but I think[ for my issue](https://github.com/dendronhq/dendron/issues/573#issuecomment-808957989) the culprit is `Dendron Markdown Preview Enhanced` taking 20-30+ seconds to start:

![image](https://user-images.githubusercontent.com/4429827/116963842-ce1f6780-ac5e-11eb-956a-3637bc1f7902.png)

**Comment by kevinslin** [comment]
Yeah, we launched an update on Monday. the preview enhanced module is a
fork and also huge so upgrading always takes a long time. we’re planning on
replacing it with a native preview later this year
