### ISSUE TITLE
Standalone desktop application

### ISSUE THREAD

**Issue by iilyak** [dendronhq/dendron#589]
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [x] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

I would like to introduce dendron for my team. However not all team members use vscode. Some users would be hard to convince to install full blown IDE which has too many buttons they would never use.

It would be great if there would be a standalone version of a desktop application. I know that some work was planned for it however I couldn't find an issue to comment on it.

## Describe the solution you'd like ##

If the standalone desktop application is in the plan I suggest to look into https://github.com/tauri-apps/tauri rather than electron app.

**Comment by af4jm** [comment]
VS is a full-blown IDE, VSCode is Notepad++ with a debugger... for me the power of Dendron is that I get a lot of stuff for free because it's built into VSCode... #1 on that list being a solid text editor with syntax highlighting & #2 being built-in Markdown preview (yes Dendron needs to extend it because of the wiki syntax--and probably a couple other things I can't think of right now--, but that's a small task compared with the enormity of building a viewer from the ground up)

I don't need something separate for my notes and I don't want something separate... I'm actually witing on the feature that will allow non-Dendron folders to be in the same VSCode workspace with Dendron

on the other hand, I do share your low opinion of Electron, and consider it the Achilles heel of VSCode

**Comment by flammehawk** [comment]
Well, as soon as dendron gets a good stable API for its server, it could be easy to just create a different frontend for dendron if the plugin is just a connector between the dendron-server and Code.

**Comment by af4jm** [comment]
not sure how I missed to notification for this last week, but...

I like Dendron because it's local only, except for however I choose to sync... and I can choose either a git server or a secure file share (I use both, with git as primary only because it allows me much easier mobile access)... if using Dendron changes to involve sending my data to Dendron's servers, I'll likely just use global find & replace to change all my wikilinks to Markdown links & leave my notes exactly where they are

I've never found exactly what I want, but I was close before I found Dendron & I'm a bit closer now... while I could write my own code to fill the gaps, I prefer not to... relying on the OS community to get me 90-95% there lets me spend my time elsewhere... or paying if I have to (e.g. Remember the Milk because they handle crazy recurrence patterns that no other task app does)... the gap between MD files in a folder & where I want to be is not big enough for me to justify spending my $ on

**Comment by flammehawk** [comment]
@af4jm
Sorry, maybe my wording wasn't correct with "Server" I meant a local server that's running on your local machine and gets started by the Plugin / CLI. You could call it the heart of dendron. If that gets stable, I see no problem with building a Standalone solution.

**Comment by af4jm** [comment]
ah, that makes sense, sorry for the confusion

**Comment by kpathakota** [comment]
Never say never but this doesn't align with our roadmap at this time. We'd like Dendron to work with existing dev tools and a standalone desktop app is antithetical to that at the moment.
