### ISSUE TITLE
Next/Previous sibling go out of order if more than 9

### ISSUE THREAD

**Issue by af4jm** [dendronhq/dendron#614]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [x] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [x] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Describe the bug

with a set of files named x.1.md through x.n.md (where n >= 10), go through the siblings with Ctrl+Shift+[ or ] 

they go out of order, despite the order being correct in Workspace Explorer

Actual Order: 28, 29, 3, 30, 31

(I have 1 set that goes to 150... and if I start from 1, it goes 1, 10, 100, 101, 102 :(

## Expected behavior

28, 29, 30, 31

## Desktop (please complete the following information)

- OS: Win10
- Browser VSCode 1.55.1
- Version 0.36.2

**Comment by kpathakota** [comment]
Yup, super clear no what needs to happen here and it is pretty annoying when navigating notes.

**Comment by ognjenio** [comment]
I usually name files that I need in order with leading zeroes:
- 0001-file
- 0002-file

And for dates yyyy-mm-dd format works well.

**Comment by kevinslin** [comment]
This is because we convert everything to string before sorting. We should have better detection for number only titles and sort by numbers instead

**Comment by hikchoi** [comment]
@af4jm @ognjenio Just letting you know that the fix has been shipped in 0.40.
Now siblings with numeric names will be sorted correctly (i.e next sibling of 29 will be 30 not 3) 😃

**Comment by af4jm** [comment]
just tried it & the command errors every time... and Dendron tree view still has the string sort order

**Comment by hikchoi** [comment]
> just tried it & the command errors every time... 

I apologize. There seems to be a regression on the `Go Previous/Next Sibling` commands introduced in the latest update. I'll let you know once again when this is fixed.

> and Dendron tree view still has the string sort order

This issue (and the fix) does not address the dendron tree view sort order. Not exactly the same, but looks like there is an open issue on document display order in the tree view already : https://github.com/dendronhq/dendron/issues/440 
If the direction that issue is going doesn't work with you, could you open a separate issue for the dendron tree view sort order?

**Comment by kevinslin** [comment]
@af4jm this has just been fixed in 0.42

**Comment by af4jm** [comment]
cool, thx... also just left some thoughts in the tree view issue
