### ISSUE TITLE
Exclude `archive.*` namespace from Dendron index

### ISSUE THREAD

**Issue by ddbrierton** [dendronhq/dendron#696]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [x] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

The `Dendron: Archive Hierarchy` command moves the current file and its descendants into the `archive.*` namespace. For this to be really useful, shouldn't the `archive.*` namespace be excluded from Dendron's index, so that they don't show up in Backlinks, the Graph, or as targets for wikilinks?

## Describe the solution you'd like ##

Please exclude the `archive.*` namespace from the Dendron index.

**Comment by flammehawk** [comment]
Please make this a config thing. 

Sometimes I see myself achieving a Hierarchy because it is stable and will no longer be changed, in that way I would still prefer to have it be indexed and allow me to quickly link to a hierarchy that got archived.

**Comment by aleksey-rowan** [comment]
Hey, @ddbrierton, there are already two issues that referred to a similar concept in the sense that they both asking for an option to exclude hierarchies (`archive` for example) from various Dendron functionalities--subtree hoisting (where you filter the tree and restrict the lookup to a certain hierarchy) and adding a sort option to remove `archive` notes from the top lookup results:

- https://github.com/dendronhq/dendron/issues/664
- https://github.com/dendronhq/dendron/issues/2561

I realize that this is is not exactly matches that ones I linked, but I think they are related enough, so that when the dev teams gets to considering/implementing this, they taking into account related concerns.

**Comment by nickolay-kondratyev** [comment]
Referenced subtree hoisting although appears to have high potential for usage is likely an **epic** level item to implement properly. 

While adding a configuration to exclude  notes from the index (or I should say NOT include into index) which start with `archive` is a couple days max worth of effort (potentially just a day).
