### ISSUE TITLE
"Will installing dendron damage my existing notes" and other questions?

### ISSUE THREAD

**Issue by ghost** [dendronhq/dendron#81]
The project looks cool, but I got some questions:

- Will installing this *brick* my previous *Zettelkasten*? Is there an easy way to go back?
- How does Dendron compare to [Foam](https://foambubble.github.io/foam/)? Is it just the hierarchy?
- How does Dendron compare to the whole *org-mode* stack? *org-roam*, *org-noter*, ...
- What are the advantages of [Markdown Notes](https://github.com/kortina/vscode-markdown-notes) over [Memo](https://github.com/svsool/vscode-memo/)? Is it just the tags?
- How does the hierarchical schema fare with something like `Öge där Szafíig.md`?
- How easy is it to link *.pdf* files? Can I open them with something like `vscode-pdf`?
- Is this free? Will it stay free?

Besides that, this looks really cool and I would love to give it a try*.

Sidenote: My current use-case is academia. I plan to add my PDF research notes as *zettel* to my *Zettelkasten*. Some *bibtex*-tooling would be cool. But I guess there might be some VSC extensions already.

*_as soon as I know that it wont permanently damage my collection.._

**Comment by kevinslin** [comment]
Thanks for the questions. See responses below:

- Will installing this brick my previous Zettelkasten? Is there an easy way to go back?
    - short answer: no but you should back it up just in case
    - long answer: https://dendron.so/notes/3bff1195-1d13-4e7a-bc2f-7e4cc617109c.html#existing-non-dendron-folder-using-dendron-change-workspace
- How does Dendron compare to Foam? Is it just the hierarchy?
    - short answer: foam is an unopinonated testing ground for roam like note taking, dendron is a highly opionated note taking tool for what I call **structured note taking**
    - long answer: https://dendron.so/notes/683740e3-70ce-4a47-a1f4-1f140e80b558.html#how-is-dendron-different-from-x-note-taking-tool
- How does Dendron compare to the whole org-mode stack? org-roam, org-noter, ...
    - doesn't have the same feature set but equivalent functionality for most features (think backlinks, tags, etc)
- What are the advantages of Markdown Notes over Memo? Is it just the tags?
    - honestly, I didn't know about Memo when I started Dendron. will need to investigate Memo before I can comment
- How does the hierarchical schema fare with something like Öge där Szafíig.md?
    - have not tried but in theory, should work out of the box
- How easy is it to link .pdf files? Can I open them with something like vscode-pdf?
    - linking and pdf files is just pasting it as a markdown link. we do have a [`open link`](https://dendron.so/notes/3472226a-ff3c-432d-bf5d-10926f39f6c2.html#other-links) command that will open a link with whatever your operating system defaults to for that particular program
- Is this free? Will it stay free?
    - short answer: yes
    - long answer: https://dendron.so/notes/683740e3-70ce-4a47-a1f4-1f140e80b558.html#is-dendron-free-will-it-stay-free

For pdfs, the way you would do it in Dendron is simply add it into the "assets" folder that comes with your notes vault. You can then link to it from within your notes. As for bibtex - you should be able to use this: https://marketplace.visualstudio.com/items?itemName=twday.bibmanager

**Comment by Annegrim** [comment]
Thanks for the explanation, I will give it a try. Two more questions:

- [layout](https://www.dendron.so/notes/3bff1195-1d13-4e7a-bc2f-7e4cc617109c.html#existing-non-dendron-folder-using-dendron-change-workspace): "if you want to publish, you can run Doctor to create the folder - note that this will also add frontmatter to all your existing notes" => Is this reversible?
- [Business model](https://www.dendron.so/notes/683740e3-70ce-4a47-a1f4-1f140e80b558.html#is-dendron-free-will-it-stay-free): Basically everything I can download from GitHub is free forever, but you will introduce additional, web-based services (synchronisation, backup, sharing, hosting, collaboration)? Also, I wish you success!

 [Sidenote: Is the [documentation](https://www.dendron.so/notes/3472226a-ff3c-432d-bf5d-10926f39f6c2.html) published as *structured notes*? Because there are some quirky topic choices. Not saying its bad, just unexpected: For example I would file *Links* and *Graph* as *Features* or *Functions* instead of *Topics*. But that is a personal choice.]

**Comment by kevinslin** [comment]
- layout: "if you want to publish, you can run Doctor to create the folder - note that this will also add frontmatter to all your existing notes" => Is this reversible?
    - right now, this isn't reversible but that would be an easy feature to add (we don't change the existing text, we just add frontmatter so the reverse would simply be removing the frontmatter). feel free to open an issue if this is something that's important to you
    - fyi, we also have a backlog item to explore storing metadata outside of the frontmatter (though this probably won't be implemented for some time unless people really want it): https://github.com/dendronhq/dendron/issues/10 
- Business model: Basically everything I can download from GitHub is free forever, but you will introduce additional, web-based services (synchronisation, backup, sharing, hosting, collaboration)? Also, I wish you success!
    - yes! i should have you write my FAQ :P and thanks!
- [Sidenote: Is the documentation published as structured notes? Because there are some quirky topic choices. Not saying its bad, just unexpected: For example I would file Links and Graph as Features or Functions instead of Topics. But that is a personal choice.]
    - yes it is. its published from this [repo](https://github.com/dendronhq/dendron-template). as for topics/features, i agree, there's distinctions to be made. trying to not overwhelm people with too many branches but will split `topics` into `topics` and `features` once the topic graph becomes unreadable :P 

![](https://foundation-prod-assetspublic53c57cce-8cpvgjldwysl.s3-us-west-2.amazonaws.com/assets/images/dendron-hierarchies.jpg)

**Comment by Annegrim** [comment]
A smart man once [wrote](https://www.dendron.so/) "But it doesn’t stop there - whereas most tools (try to make it) easy to get notes in, they tend to make it hard to get them back out later, and it only gets worse as you add more notes. Dendron helps you get notes back out and works better the more notes you have.", so I definitively believe that an ability to remove the frontmatter is needed. => [I created an issue](https://github.com/dendronhq/dendron/issues/86)

Also if you need help with FAQ/texts, it might be a good idea to take a look at what other projects in the same space write (I find my stuff based on this [list](https://www.notion.so/db13644f08144495ad9877f217a161a1?v=ff6777802811416ba08dc114e0b11837) here). Beyond that, I got a bit time to help with writing.

**Comment by kevinslin** [comment]
dunno how smart that man was but point taken :) 

will be doing some thinking about this over the weekend!

and thanks for the tip about faqs. will take a look at the notion. would love any help you're willing to provide. instructions to contribute to the docs are [here](https://www.dendron.so/notes/125c990b-6fe7-4ada-a65f-44cbde8b33f0.html)
