### ISSUE TITLE
Show vault name in VSCode suggestion when typing wiki-links.

### ISSUE THREAD

**Issue by agichim** [dendronhq/dendron#952]
## Please Select if your Request is Either something new or an Enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applys ← **APPLIES** to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [x] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

I have files with the same name in multiple vault. 

## Describe the solution you'd like ##

When I use VSCode suggestion I'd like to see next to the file name the name of the vault. 

## Additional context ##

![image](https://user-images.githubusercontent.com/51931067/125167080-a4227e00-e196-11eb-82e7-aaffbbc42a6d.png)

**Comment by SeriousBug** [comment]
This is planned to be added, please see #887 . VSCode 1.58 adds support for displaying extra information on autocomplete options, so we will be adding this feature after switching Dendron to 1.58.

I'm closing this issue since it's a duplicate, but please feel free to add more feedback to the issue I linked.
