### ISSUE TITLE
DeprecationWarning: Buffer()

### ISSUE THREAD

**Issue by golergka** [dendronhq/dendron#973]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

DeprecationWarning in console when starting Dendron in debug mode.

## To Reproduce

1. Go through steps described [in this page](https://wiki.dendron.so/notes/3489b652-cd0e-4ac8-a734-08094dc043eb.html) up to the point "Start debugging"
2. Look in the logs

## Expected behavior

No errors, warnings or deprecations

## Actual behaviour

```
(node:98848) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code - Insiders Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
```

## Desktop (please complete the following information)

- OS: macOS 11.4
- Browser: Safari
- Version: 391c6cd3 

## Dendron Log file

[dendron.log](https://github.com/dendronhq/dendron/files/6812690/dendron.log)

**Comment by hikchoi** [comment]
Hey, thanks for the report.
This issue is from a module that VSCode depends on, which is depending on another module which the maintainer has no intention to fix.
You can follow what's going on here: https://github.com/microsoft/vscode/issues/82524

No part of our code uses the deprecated `Buffer` method there's nothing we can do to make this go away for now.
